# Generated by Django 4.1.3 on 2022-12-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_profile_alter_blog_author_delete_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="firstname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lastname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
