# Generated by Django 4.1.4 on 2022-12-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="default_avatar.png", null=True, upload_to="avatars"
            ),
        ),
    ]
