# Generated by Django 4.1.4 on 2022-12-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="user.png", null=True, upload_to="avatars"),
        ),
    ]
