# Generated by Django 4.1.4 on 2022-12-20 09:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
